function mvwarranty()
%MVWARRANTY -- warranty information
%

%	$Id: mvwarranty.m,v 1.2 2001/12/04 10:19:37 rune Exp $	

disp('			    NO WARRANTY')
disp(' ')
disp('BECAUSE THE PROGRAM IS LICENSED FREE OF CHARGE, THERE IS NO')
disp('WARRANTY FOR THE PROGRAM, TO THE EXTENT PERMITTED BY APPLICABLE')
disp('LAW.  EXCEPT WHEN OTHERWISE STATED IN WRITING THE COPYRIGHT')
disp('HOLDERS AND/OR OTHER PARTIES PROVIDE THE PROGRAM "AS IS"')
disp('WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED OR IMPLIED,')
disp('INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF')
disp('MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.  THE')
disp('ENTIRE RISK AS TO THE QUALITY AND PERFORMANCE OF THE PROGRAM')
disp('IS WITH YOU.  SHOULD THE PROGRAM PROVE DEFECTIVE, YOU ASSUME')
disp('THE COST OF ALL NECESSARY SERVICING, REPAIR OR CORRECTION.')
disp(' ')
disp('IN NO EVENT UNLESS REQUIRED BY APPLICABLE LAW OR AGREED TO')
disp('IN WRITING WILL ANY COPYRIGHT HOLDER, OR ANY OTHER PARTY WHO MAY')
disp('MODIFY AND/OR REDISTRIBUTE THE PROGRAM AS PERMITTED ABOVE, BE') 
disp('LIABLE TO YOU FOR DAMAGES, INCLUDING ANY GENERAL, SPECIAL, ')
disp('INCIDENTAL OR CONSEQUENTIAL DAMAGES ARISING OUT OF THE USE OR') 
disp('INABILITY TO USE THE PROGRAM (INCLUDING BUT NOT LIMITED TO LOSS') 
disp('OF DATA OR DATA BEING RENDERED INACCURATE OR LOSSES SUSTAINED BY')
disp('YOU OR THIRD PARTIES OR A FAILURE OF THE PROGRAM TO OPERATE WITH') 
disp('ANY OTHER PROGRAMS), EVEN IF SUCH HOLDER OR OTHER PARTY HAS BEEN')
disp('ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.')
